### ISSUE TITLE
[Feat] Add .gitignore

### ISSUE THREAD

**Issue by nomatterjun** [inu-appcenter/iOS-study-14.5th#10]
## 📋 이슈 내용

`.gitignore` 파일 적용해주세요.. 🙏

## 📚 레퍼런스
[gitignore.io](https://www.toptal.com/developers/gitignore)

**Comment by vhzkclq0705** [comment]
헉 지금 봤네요 적용시켜드릴게요
했지만 이미 추가하셨네요!! 감사합니다ㅠ

**Comment by nomatterjun** [comment]
> 헉 지금 봤네요 적용시켜드릴게요 했지만 이미 추가하셨네요!! 감사합니다ㅠ

감사합니다! 🥰 👍👍
